baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Lasthash | New Generation Technologies"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "M38, Sector-12 , Pratap Vihar Ghaziabad UP-201009"
author = "Shiv Singh"
copyright = "Copyright © 2017-2021 Lasthash"
description = "This is meta description"
email = "contact@lasthash.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/lasthash.png"
phone = "+91 79823 77273"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = ""
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/lasthash"
icon = "ti-facebook"
[[params.social]]
URL = "#"
icon = "ti-instagram"
